### ISSUE TITLE
Update package.swift to v200.1

### ISSUE THREAD

**Issue by laurenwinter** [Esri/arcgis-maps-sdk-swift-toolkit#255]
I've been having a lot of problems using a local clone of this package because I need to use runtime 200.1. Could you update your package .swift file so that it uses v200.1?

**Comment by yo1995** [comment]
I'm wondering if keeping the package dependency as local package on `v.next` helps in your case Lauren. In that way, you can always pull the latest Swift API and build the toolkit upon it. However, if you want to use the daily build binary output, then it is not feasible because we aren't allowed to exposed devtopia links on public GitHub.

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/228a68149507e2deb1f27d49b180f2dc945b2f38/Package.swift#L32

**Comment by dfeinzimer** [comment]
Closing - the package is now at 200.1.
