### ISSUE TITLE
`Popup` - Fix formatting for local items

### ISSUE THREAD

**Issue by des12437** [Esri/arcgis-maps-sdk-swift-toolkit#546]
The `Popup` component looks unformatted for a geoElement loaded from an offline mobile map package. Here is the unformatted  popup compared to a formatted popup from the Examples app for reference:
<img src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/117859673/28dfdf7e-c5e3-4830-8c62-23993d9d2863" width="300">          <img src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/117859673/732faa16-4555-422f-8406-7d0ad7180166" width="300">

This issue can be reproduced in the project located at `des12437/Geotriggers`. Tapping on a notification in the app will present an unformatted popup.

**Comment by mhdostal** [comment]
So that is expected. The Popup in the Examples app is using a `PopupDefinition` for the feature's layer which was stored in the web map. The popup definition defines the "elements" in the popup, such as the text description, media (images), and media (charts).

Without a popup definition you simply get a list of all the fields, which is what you're seeing.

Was there a reference implementation of this demo that provided a nicer-looking popup?

**Comment by des12437** [comment]
> Was there a reference implementation of this demo that provided a nicer-looking popup?

Yes, here is a reference image. It looks similar to a webpage, although this feature is derived from an offline map.

<img width="300" alt="Screenshot 2023-12-14 at 4 19 47 PM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/117859673/4b079868-97d2-4bd0-9a4f-747d95799ca4">

**Comment by mhdostal** [comment]
Ok, got it. Since the `fenceNotificationInfo.fenceGeoElement` is actually an `ArcGISFeature` you can get the `PopupDefinition` from the feature's table and pass that in to the `Popup` initializer. You then get this:

![image](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/3998072/6686033f-8bcc-48d1-acfb-96db63ae7af1)

Here's the code:

```
let popupDefinition = (fenceNotificationInfo.fenceGeoElement as? ArcGISFeature)?.table?.popupDefinition
popup = Popup(geoElement: fenceNotificationInfo.fenceGeoElement, definition: popupDefinition)
```

**Comment by des12437** [comment]
> Ok, got it. Since the `fenceNotificationInfo.fenceGeoElement` is actually an `ArcGISFeature` you can get the `PopupDefinition` from the feature's table and pass that in to the `Popup` initializer. You then get this:

Thank you for the explanation. Since the behavior is expected when using `Popup(geoElement:)` and `Popup(geoElement: definition:)` I will close out this issue.
